# Generated by Django 5.0.7 on 2024-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Direccion', models.TextField()),
                ('telefono', models.IntegerField(max_length=20)),
            ],
        ),
    ]
