# Generated by Django 5.0.7 on 2024-09-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
