# Generated by Django 5.0.7 on 2024-09-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_pedido_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='telefono',
        ),
    ]
